### ISSUE TITLE
Trouble in Demo No.13 ModuleLoader

### ISSUE THREAD

**Issue by rzgrzg** [vdisasm/pe-image-for-delphi#4]
Dear you,I,ve got some Exeption for Read error in following Code in PE.ExecutableLoader.pas
    else if FPE.IsDLL then
    begin
      FPE.Msg.Write('Calling DLL Entry with DLL_PROCESS_ATTACH.');
      EntryOK := TDLLEntry(FEntry)(FInstance, DLL_PROCESS_ATTACH, nil);  <---
So,I steped into the FEntry to See How can I solve this by myself.
058635BE    8F43 18         pop     dword ptr [ebx+18]
058635C1    896B 14         mov     dword ptr [ebx+14], ebp
058635C4    8943 08         mov     dword ptr [ebx+8], eax
058635C7    8953 10         mov     dword ptr [ebx+10], edx
058635CA    8D4D C0         lea     ecx, dword ptr [ebp-40]
058635CD    890B            mov     dword ptr [ebx], ecx
058635CF    E8 54DAFFFF     call    05861028  <<<

05861028  - FF25 4CB18605   jmp     dword ptr [586B14C]
ds:[05A2B14C]=0000B2CA which should be 05A260E8
somebody can help me?

**Comment by vdisasm** [comment]
Hi, I don't support the project anymore, though please create minimal project to reproduce the problem and attach it here. Maybe I or someone else can then help you faster.

**Comment by vdisasm** [comment]
The project isn't really supported. But I've added few changes (related to resolving imports). Probably should fix the issue.

**Comment by vdisasm** [comment]
ok, closed for now, reopen if need
