### ISSUE TITLE
is bug?

### ISSUE THREAD

**Issue by laoqiuqiu** [vdisasm/pe-image-for-delphi#5]
PE. Image.pas
Line 1696:FSections.Insert (0, SEC);

Executing this line of code Img.FileHeader.NumberOfSections will be 1 more than the actual value

**Comment by vdisasm** [comment]
You're right.
There was concept of "virtual" sections planned, like Header or Overlay (or Address Ranges rather than Sections).
But I probably won't go back for this project, so for now I'll comment out calling LoadingAddHeaderAsASection.

Thanks for finding this.
